apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elayvilkom-db-pvc
  namespace: elayvilkom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc-nitzanim
